name: Inject
on:
  push:
    branches:
      - 'master'
jobs:
  inject:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - repo: commonquail/gh-consumer-canary1
            is_canary: true
          #- repo: commonquail/gh-consumer-canary2
          #  is_canary: true
          #- repo: commonquail/gh-consumer-consumer1
          #- repo: commonquail/gh-consumer-consumer2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        shell: bash
        run: |
          echo "TARGET_BRANCH_NAME_DESTINATION=master" >> $GITHUB_ENV
          echo "TARGET_BRANCH_NAME_SOURCE=b-inject" >> $GITHUB_ENV
          echo "GIT_AUTHOR_EMAIL=github-actions[bot]@users.noreply.github.com" >> $GITHUB_ENV
          echo "GIT_AUTHOR_NAME=github-actions[bot]" >> $GITHUB_ENV
          echo "GIT_COMMITTER_EMAIL=github-actions[bot]@users.noreply.github.com" >> $GITHUB_ENV
          echo "GIT_COMMITTER_NAME=github-actions[bot]" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.target.repo }}
          path: ${{ matrix.target.repo }}
          token: ${{ secrets.INJECT_TOKEN }}

      - name: Reset target
        shell: bash
        working-directory: ./${{ matrix.target.repo }}
        run:
          git push origin --delete "$TARGET_BRANCH_NAME_SOURCE" || true

      - name: Hallucinate content
        shell: bash
        working-directory: ./${{ matrix.target.repo }}
        run: |
          date --iso=seconds > content

      - name: Stage content
        shell: bash
        working-directory: ./${{ matrix.target.repo }}
        run: |
          git switch --create "$TARGET_BRANCH_NAME_SOURCE"
          git add content

      - name: Inject content
        shell: bash
        working-directory: ./${{ matrix.target.repo }}
        run: |
          git commit -m "Hello from $(cat content)"

      - name: Push change
        shell: bash
        working-directory: ./${{ matrix.target.repo }}
        run: |
          git push origin "$TARGET_BRANCH_NAME_SOURCE"
